version: '3.8'

services:
  card:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    container_name: card-service
    depends_on:
      - card-database
    networks:
      - card-network
      - microservices

  card-database:
    image: postgres:16
    environment:
      POSTGRES_DB: card_db
      POSTGRES_USER: card
      POSTGRES_PASSWORD: card
    container_name: card-database
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - card-network

volumes:
  pg_volume:

networks:
  card-network:
  microservices:
    external: true
